local A=AzerothAdminMoP548
A:RegisterLocale("koKR",{["UX_GM_ISLAND"]="GM의 섬",["UX_ALL_COMMANDS"]="GM명령어(전체)",["UX_ALL_BINDINGS"]="전체 단축키 설정",["UX_BINDINGS_UNAVAILABLE"]="게임 메뉴에서 단축키 설정을 열어 주세요.",["UX_SELF_COMBAT"]="전투 종료 후 사용해 주세요.",["UX_SELF_FAILED"]="본인 선택을 확인하지 못해 요청을 보내지 않았습니다.",["UX_REQUESTED"]="요청을 보냈습니다. 서버 응답 후 반영됩니다.",["UX_REQUEST_FAILED"]="요청하지 못했습니다. 대화창 안내를 확인해 주세요.",["UX_LEARN_SPELL"]="스킬 습득",["UX_KNOWN"]="습득함",["UX_CURRENT_RANK"]="현재 습득: %s",["UX_RANK_NUMBER"]="%d 단계",["UX_SINGLE_RANK"]="단일 단계",["UX_PROF_TRAINING"]="숙련 등급",["UX_LEARN_TIER"]="등급 습득",["UX_MAX_SKILL"]="숙련 최대",["UX_UTILITIES"]="GM 편의 기능",["UX_COOLDOWN"]="재사용 시간 초기화",["UX_DISMOUNT"]="탈것 내리기",["UX_DEMORPH"]="외형 복원",["UX_WATERWALK"]="수면 보행 ON/OFF",["UX_SAVE"]="캐릭터 저장",["UX_APPLIES_SELF"]="클릭하면 본인 캐릭터에 적용합니다.",["SPY_READY"]=""})
A:RegisterLocale("enUS",{["UX_GM_ISLAND"]="GM Island",["UX_ALL_COMMANDS"]="GM commands (all)",["UX_ALL_BINDINGS"]="All key bindings",["UX_BINDINGS_UNAVAILABLE"]="Open Key Bindings from the game menu.",["UX_SELF_COMBAT"]="Use this after combat ends.",["UX_SELF_FAILED"]="Could not select your character; no request was sent.",["UX_REQUESTED"]="Request sent. Waiting for the server update.",["UX_REQUEST_FAILED"]="Request failed. Check the chat message.",["UX_LEARN_SPELL"]="Learn spell",["UX_KNOWN"]="Learned",["UX_CURRENT_RANK"]="Learned rank: %s",["UX_RANK_NUMBER"]="Rank %d",["UX_SINGLE_RANK"]="Single rank",["UX_PROF_TRAINING"]="Profession ranks",["UX_LEARN_TIER"]="Learn rank",["UX_MAX_SKILL"]="Max skill",["UX_UTILITIES"]="GM utilities",["UX_COOLDOWN"]="Reset cooldowns",["UX_DISMOUNT"]="Dismount",["UX_DEMORPH"]="Restore appearance",["UX_WATERWALK"]="Water walking",["UX_SAVE"]="Save character",["UX_APPLIES_SELF"]="Click to apply to your character.",["SPY_READY"]=""})
A:RegisterLocale("zhCN",{["UX_GM_ISLAND"]="GM岛",["UX_ALL_COMMANDS"]="GM命令（全部）",["UX_ALL_BINDINGS"]="全部按键设置",["UX_BINDINGS_UNAVAILABLE"]="请从游戏菜单打开按键设置。",["UX_SELF_COMBAT"]="请在战斗结束后使用。",["UX_SELF_FAILED"]="无法确认自身目标，未发送请求。",["UX_REQUESTED"]="已发送请求，等待服务器更新。",["UX_REQUEST_FAILED"]="请求失败，请查看聊天提示。",["UX_LEARN_SPELL"]="学习法术",["UX_KNOWN"]="已学会",["UX_CURRENT_RANK"]="当前等级：%s",["UX_RANK_NUMBER"]="等级%d",["UX_SINGLE_RANK"]="单一等级",["UX_PROF_TRAINING"]="专业等级",["UX_LEARN_TIER"]="学习等级",["UX_MAX_SKILL"]="提升熟练度",["UX_UTILITIES"]="GM便捷功能",["UX_COOLDOWN"]="重置冷却",["UX_DISMOUNT"]="下坐骑",["UX_DEMORPH"]="恢复外形",["UX_WATERWALK"]="水上行走开/关",["UX_SAVE"]="保存角色",["UX_APPLIES_SELF"]="点击后应用于自身角色。",["SPY_READY"]=""})
A:RegisterLocale("zhTW",{["UX_GM_ISLAND"]="GM島",["UX_ALL_COMMANDS"]="GM命令（全部）",["UX_ALL_BINDINGS"]="全部快捷鍵設定",["UX_BINDINGS_UNAVAILABLE"]="請從遊戲選單開啟快捷鍵設定。",["UX_SELF_COMBAT"]="請在戰鬥結束後使用。",["UX_SELF_FAILED"]="無法確認自身目標，未送出請求。",["UX_REQUESTED"]="已送出請求，等待伺服器更新。",["UX_REQUEST_FAILED"]="請求失敗，請查看聊天提示。",["UX_LEARN_SPELL"]="學習法術",["UX_KNOWN"]="已學會",["UX_CURRENT_RANK"]="目前等級：%s",["UX_RANK_NUMBER"]="等級%d",["UX_SINGLE_RANK"]="單一等級",["UX_PROF_TRAINING"]="專業等級",["UX_LEARN_TIER"]="學習等級",["UX_MAX_SKILL"]="提升熟練度",["UX_UTILITIES"]="GM便利功能",["UX_COOLDOWN"]="重設冷卻",["UX_DISMOUNT"]="下坐騎",["UX_DEMORPH"]="恢復外形",["UX_WATERWALK"]="水上行走開/關",["UX_SAVE"]="儲存角色",["UX_APPLIES_SELF"]="點擊後套用至自身角色。",["SPY_READY"]=""})
A:RegisterLocale("ruRU",{["UX_GM_ISLAND"]="Остров GM",["UX_ALL_COMMANDS"]="Все команды GM",["UX_ALL_BINDINGS"]="Все клавиши",["UX_BINDINGS_UNAVAILABLE"]="Откройте настройки клавиш в меню игры.",["UX_SELF_COMBAT"]="Используйте после боя.",["UX_SELF_FAILED"]="Не удалось выбрать себя; запрос не отправлен.",["UX_REQUESTED"]="Запрос отправлен. Ожидание ответа сервера.",["UX_REQUEST_FAILED"]="Запрос не отправлен. Проверьте сообщение в чате.",["UX_LEARN_SPELL"]="Выучить",["UX_KNOWN"]="Изучено",["UX_CURRENT_RANK"]="Изучено: %s",["UX_RANK_NUMBER"]="Ранг %d",["UX_SINGLE_RANK"]="Один ранг",["UX_PROF_TRAINING"]="Уровни профессии",["UX_LEARN_TIER"]="Выучить ранг",["UX_MAX_SKILL"]="Макс. навык",["UX_UTILITIES"]="Инструменты GM",["UX_COOLDOWN"]="Сброс перезарядки",["UX_DISMOUNT"]="Спешиться",["UX_DEMORPH"]="Вернуть облик",["UX_WATERWALK"]="Хождение по воде",["UX_SAVE"]="Сохранить героя",["UX_APPLIES_SELF"]="Применить к своему персонажу.",["SPY_READY"]=""})
A:RegisterLocale("koKR",{["UX_QUEST_LOG_ONLY"]="L키 퀘스트 목록에만 연결됩니다. NPC 대화 중에는 숨깁니다."})
A:RegisterLocale("enUS",{["UX_QUEST_LOG_ONLY"]="Attached only to the quest log (L). Hidden during NPC dialogue."})
A:RegisterLocale("zhCN",{["UX_QUEST_LOG_ONLY"]="仅跟随任务日志（L），与NPC对话时隐藏。"})
A:RegisterLocale("zhTW",{["UX_QUEST_LOG_ONLY"]="僅跟隨任務日誌（L），與NPC對話時隱藏。"})
A:RegisterLocale("ruRU",{["UX_QUEST_LOG_ONLY"]="Показывается только у журнала заданий (L), скрывается при разговоре с НИП."})
A.textLocaleKeys=A.textLocaleKeys or {}
for _,locale in ipairs({"koKR","enUS","zhCN","zhTW","ruRU"})do for key,value in pairs(A.locales[locale])do if key:match("^UX_") and value~=""then A.textLocaleKeys[value]=key end end end
