local A = AzerothAdminMoP548
local S = A.Security
A:RegisterCategory("gm", "CAT_GM", 10, "Interface\\Icons\\INV_Misc_Gear_01", nil)
A:RegisterCategory("movement", "CAT_MOVEMENT", 20, "Interface\\Icons\\INV_Misc_Map_01", nil)
A:RegisterCategory("character", "CAT_CHARACTER", 30, "Interface\\Icons\\INV_Misc_Book_09", nil)
A:RegisterCategory("target", "CAT_TARGET", 40, "Interface\\Icons\\INV_Misc_Head_Dragon_01", nil)
A:RegisterCategory("search", "CAT_SEARCH", 50, "Interface\\Icons\\INV_Misc_Spyglass_02", nil)
A:RegisterCategory("items", "CAT_ITEMS", 60, "Interface\\Icons\\INV_Misc_Bag_10_Blue", nil)
A:RegisterCategory("quests", "CAT_QUESTS", 70, "Interface\\Icons\\INV_Misc_Note_02", nil)
A:RegisterCategory("recovery", "CAT_RECOVERY", 80, "Interface\\Icons\\Spell_Holy_Resurrection", nil)
A:RegisterCategory("system", "CAT_SYSTEM", 90, "Interface\\Icons\\INV_Misc_Gear_01", nil)
A:RegisterCategory("teleports", "CAT_TELEPORTS", 100, "Interface\\Icons\\INV_Misc_Map_01", "OpenTeleportWindow")
A:RegisterCategory("professions", "CAT_PROFESSIONS", 110, "Interface\\Icons\\Trade_Engineering", "OpenProfessionWindow")
A:RegisterCategory("database", "CAT_DATABASE", 120, "Interface\\Icons\\INV_Misc_Book_11", "OpenDatabaseWindow")

A:RegisterCommand({ id = "gm_on", labelKey = "CMD_GM_ON", command = ".gm on", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_off", labelKey = "CMD_GM_OFF", command = ".gm off", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_chat_on", labelKey = "CMD_GM_CHAT_ON", command = ".gm chat on", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_chat_off", labelKey = "CMD_GM_CHAT_OFF", command = ".gm chat off", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_fly_on", labelKey = "CMD_FLY_ON", command = ".gm fly on", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_fly_off", labelKey = "CMD_FLY_OFF", command = ".gm fly off", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_visible_on", labelKey = "CMD_VISIBLE_ON", command = ".gm visible on", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gm_visible_off", labelKey = "CMD_VISIBLE_OFF", command = ".gm visible off", security = S.GAMEMASTER, source = "cs_gm.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_god_on", labelKey = "CMD_GOD_ON", command = ".cheat god on", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_god_off", labelKey = "CMD_GOD_OFF", command = ".cheat god off", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_waterwalk_on", labelKey = "CMD_WATERWALK_ON", command = ".cheat waterwalk on", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_waterwalk_off", labelKey = "CMD_WATERWALK_OFF", command = ".cheat waterwalk off", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_cooldown_on", labelKey = "CMD_COOLDOWN_ON", command = ".cheat cooldown on", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_cooldown_off", labelKey = "CMD_COOLDOWN_OFF", command = ".cheat cooldown off", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_casttime_on", labelKey = "CMD_CASTTIME_ON", command = ".cheat casttime on", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_casttime_off", labelKey = "CMD_CASTTIME_OFF", command = ".cheat casttime off", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_power_on", labelKey = "CMD_POWER_ON", command = ".cheat power on", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_power_off", labelKey = "CMD_POWER_OFF", command = ".cheat power off", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "cheat_status", labelKey = "CMD_CHEAT_STATUS", command = ".cheat status", security = S.GAMEMASTER, source = "cs_cheat.cpp", category = "gm", style = "utility" })
A:RegisterCommand({ id = "gps", labelKey = "CMD_GPS", command = ".gps", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "movement", style = "utility" })
A:RegisterCommand({ id = "recall", labelKey = "CMD_RECALL", command = ".recall", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "movement", style = "utility" })
A:RegisterCommand({ id = "appear", labelKey = "CMD_APPEAR", command = ".appear", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "movement", promptKey = "PROMPT_PLAYER", style = "utility" })
A:RegisterCommand({ id = "summon", labelKey = "CMD_SUMMON", command = ".summon", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "movement", promptKey = "PROMPT_PLAYER", style = "utility" })
A:RegisterCommand({ id = "tele", labelKey = "CMD_TELE", command = ".tele", security = S.GAMEMASTER, source = "cs_tele.cpp", category = "movement", promptKey = "PROMPT_TELEPORT", style = "utility" })
A:RegisterCommand({ id = "go_xyz", labelKey = "CMD_GO_XYZ", command = ".go xyz", security = S.GAMEMASTER, source = "cs_go.cpp", category = "_internal", hidden = true, style = "utility" })
A:RegisterCommand({ id = "go_creature", labelKey = "CMD_GO_CREATURE", command = ".go creature", security = S.GAMEMASTER, source = "cs_go.cpp", category = "_internal", hidden = true, style = "utility" })
A:RegisterCommand({ id = "go_object", labelKey = "CMD_GO_OBJECT", command = ".go object", security = S.GAMEMASTER, source = "cs_go.cpp", category = "_internal", hidden = true, style = "utility" })
A:RegisterCommand({ id = "lookup_tele", labelKey = "CMD_LOOKUP_TELE", command = ".lookup tele", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "movement", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "speed_1", labelKey = "CMD_SPEED_1", command = ".modify speed all 1", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "movement", style = "utility" })
A:RegisterCommand({ id = "speed_3", labelKey = "CMD_SPEED_3", command = ".modify speed all 3", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "movement", style = "utility" })
A:RegisterCommand({ id = "dismount", labelKey = "CMD_DISMOUNT", command = ".dismount", security = S.PLAYER, source = "cs_misc.cpp", category = "movement" })
A:RegisterCommand({ id = "unstuck", labelKey = "CMD_UNSTUCK", command = ".unstuck", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "movement", style = "reward" })
A:RegisterCommand({ id = "cometome", labelKey = "CMD_COMETOME", command = ".cometome", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "movement", style = "utility" })
A:RegisterCommand({ id = "teleport_window", labelKey = "CMD_TELEPORT_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "movement", action = "OpenTeleportWindow", style = "utility" })
A:RegisterCommand({ id = "levelup", labelKey = "CMD_LEVELUP", command = ".levelup", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_LEVEL", style = "reward" })
A:RegisterCommand({ id = "character_level", labelKey = "CMD_CHAR_LEVEL", command = ".character level", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_LEVEL", style = "reward" })
A:RegisterCommand({ id = "character_rename", labelKey = "CMD_RENAME", command = ".character rename", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_PLAYER" })
A:RegisterCommand({ id = "character_customize", labelKey = "CMD_CUSTOMIZE", command = ".character customize", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_PLAYER" })
A:RegisterCommand({ id = "character_changefaction", labelKey = "CMD_CHANGEFACTION", command = ".character changefaction", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_PLAYER" })
A:RegisterCommand({ id = "character_changerace", labelKey = "CMD_CHANGERACE", command = ".character changerace", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_PLAYER" })
A:RegisterCommand({ id = "character_changeclass", labelKey = "CMD_CHANGECLASS", command = ".character changeclass", security = S.GAMEMASTER, source = "cs_character.cpp", category = "character", promptKey = "PROMPT_PLAYER" })
A:RegisterCommand({ id = "maxskill", labelKey = "CMD_MAXSKILL", command = ".maxskill", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "character", style = "reward" })
A:RegisterCommand({ id = "repairitems", labelKey = "CMD_REPAIR", command = ".repairitems", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "character", style = "reward" })
A:RegisterCommand({ id = "save", labelKey = "CMD_SAVE", command = ".save", security = S.PLAYER, source = "cs_misc.cpp", category = "character" })
A:RegisterCommand({ id = "pinfo", labelKey = "CMD_PINFO", command = ".pinfo", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "character", promptKey = "PROMPT_PLAYER" })
A:RegisterCommand({ id = "bank_window", labelKey = "CMD_BANK", command = "", security = S.MODERATOR, source = "cs_misc.cpp", category = "character", action = "OpenBank", style = "utility" })
A:RegisterCommand({ id = "bank", labelKey = "CMD_BANK", command = ".bank", security = S.MODERATOR, source = "cs_misc.cpp", category = "_internal", hidden = true, style = "utility" })
A:RegisterCommand({ id = "modify_money", labelKey = "CMD_MONEY", command = ".modify money", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "character", promptKey = "PROMPT_MONEY", style = "reward" })
A:RegisterCommand({ id = "modify_hp", labelKey = "CMD_HP", command = ".modify hp", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "character", promptKey = "PROMPT_HP", style = "reward" })
A:RegisterCommand({ id = "modify_mana", labelKey = "CMD_MANA", command = ".modify mana", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "character", promptKey = "PROMPT_MANA", style = "reward" })
A:RegisterCommand({ id = "die", labelKey = "CMD_DIE", command = ".die", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", dangerous = false, style = "danger" })
A:RegisterCommand({ id = "revive", labelKey = "CMD_REVIVE", command = ".revive", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", action = "ReviveSmart", style = "reward" })
A:RegisterCommand({ id = "respawn", labelKey = "CMD_RESPAWN", command = ".respawn", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", style = "reward" })
A:RegisterCommand({ id = "combatstop", labelKey = "CMD_COMBATSTOP", command = ".combatstop", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", style = "utility" })
A:RegisterCommand({ id = "freeze", labelKey = "CMD_FREEZE", command = ".freeze", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", promptKey = "PROMPT_PLAYER", style = "danger" })
A:RegisterCommand({ id = "unfreeze", labelKey = "CMD_UNFREEZE", command = ".unfreeze", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", promptKey = "PROMPT_PLAYER", style = "reward" })
A:RegisterCommand({ id = "guid", labelKey = "CMD_GUID", command = ".guid", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", style = "utility" })
A:RegisterCommand({ id = "distance", labelKey = "CMD_DISTANCE", command = ".distance", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", style = "utility" })
A:RegisterCommand({ id = "aura", labelKey = "CMD_AURA", command = ".aura", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", promptKey = "PROMPT_AURA", style = "utility" })
A:RegisterCommand({ id = "unaura", labelKey = "CMD_UNAURA", command = ".unaura", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", promptKey = "PROMPT_AURA", style = "utility" })
A:RegisterCommand({ id = "morph", labelKey = "CMD_MORPH", command = ".morph", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "target", promptKey = "PROMPT_MORPH", style = "utility" })
A:RegisterCommand({ id = "demorph", labelKey = "CMD_DEMORPH", command = ".demorph", security = S.GAMEMASTER, source = "cs_modify.cpp", category = "target", style = "utility" })
A:RegisterCommand({ id = "possess", labelKey = "CMD_POSSESS", command = ".possess", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", dangerous = false, style = "danger" })
A:RegisterCommand({ id = "unpossess", labelKey = "CMD_UNPOSSESS", command = ".unpossess", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "target", style = "reward" })
A:RegisterCommand({ id = "creature_window", labelKey = "CMD_CREATURE_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "target", action = "OpenCreatureWindow", style = "utility" })
A:RegisterCommand({ id = "lookup_item", labelKey = "CMD_LOOKUP_ITEM", command = ".lookup item", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_itemset", labelKey = "CMD_LOOKUP_ITEMSET", command = ".lookup itemset", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_quest", labelKey = "CMD_LOOKUP_QUEST", command = ".lookup quest", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_creature", labelKey = "CMD_LOOKUP_CREATURE", command = ".lookup creature", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_object", labelKey = "CMD_LOOKUP_OBJECT", command = ".lookup object", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_spell", labelKey = "CMD_LOOKUP_SPELL", command = ".lookup spell", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_skill", labelKey = "CMD_LOOKUP_SKILL", command = ".lookup skill", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_area", labelKey = "CMD_LOOKUP_AREA", command = ".lookup area", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_map", labelKey = "CMD_LOOKUP_MAP", command = ".lookup map", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_title", labelKey = "CMD_LOOKUP_TITLE", command = ".lookup title", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_event", labelKey = "CMD_LOOKUP_EVENT", command = ".lookup event", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_faction", labelKey = "CMD_LOOKUP_FACTION", command = ".lookup faction", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "lookup_taxinode", labelKey = "CMD_LOOKUP_TAXI", command = ".lookup taxinode", security = S.GAMEMASTER, source = "cs_lookup.cpp", category = "search", promptKey = "PROMPT_LOOKUP", style = "utility" })
A:RegisterCommand({ id = "search_window", labelKey = "CMD_SEARCH_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "search", action = "OpenSearchWindow", style = "utility" })
A:RegisterCommand({ id = "item_browser", labelKey = "CMD_ITEM_BROWSER", command = "", security = S.PLAYER, source = "addon", category = "items", action = "OpenItemBrowser", style = "utility" })
A:RegisterCommand({ id = "additem", labelKey = "CMD_ADDITEM", command = ".additem", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "items", promptKey = "PROMPT_ITEM", style = "reward" })
A:RegisterCommand({ id = "additemset", labelKey = "CMD_ADDITEMSET", command = ".additemset", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "items", promptKey = "PROMPT_ITEMSET", style = "reward" })
A:RegisterCommand({ id = "itemmove", labelKey = "CMD_ITEMMOVE", command = ".itemmove", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "items", promptKey = "PROMPT_ITEMMOVE" })
A:RegisterCommand({ id = "itemspecs", labelKey = "CMD_ITEM_SPECS", command = ".itemspecs", security = S.ADMINISTRATOR, source = "cs_misc.cpp", category = "items", promptKey = "PROMPT_ITEM" })
A:RegisterCommand({ id = "learn", labelKey = "CMD_LEARN", command = ".learn", security = S.GAMEMASTER, source = "cs_learn.cpp", category = "items", promptKey = "PROMPT_SPELL", style = "reward" })
A:RegisterCommand({ id = "unlearn", labelKey = "CMD_UNLEARN", command = ".unlearn", security = S.GAMEMASTER, source = "cs_learn.cpp", category = "items", promptKey = "PROMPT_SPELL", style = "danger" })
A:RegisterCommand({ id = "learn_all_recipes", labelKey = "CMD_LEARN_RECIPES", command = ".learn all recipes", security = S.GAMEMASTER, source = "cs_learn.cpp", category = "items", style = "reward" })
A:RegisterCommand({ id = "learn_all_crafts", labelKey = "CMD_LEARN_CRAFTS", command = ".learn all crafts", security = S.GAMEMASTER, source = "cs_learn.cpp", category = "items", style = "reward" })
A:RegisterCommand({ id = "quest_helper", labelKey = "CMD_QUEST_HELPER", command = "", security = S.PLAYER, source = "addon", category = "quests", action = "OpenQuestHelper", style = "utility" })
A:RegisterCommand({ id = "quest_add", labelKey = "CMD_QUEST_ADD", command = ".quest add", security = S.ADMINISTRATOR, source = "cs_quest.cpp", category = "quests", promptKey = "PROMPT_QUEST", style = "reward", notes = "Requires selected player" })
A:RegisterCommand({ id = "quest_complete", labelKey = "CMD_QUEST_COMPLETE", command = ".quest complete", security = S.ADMINISTRATOR, source = "cs_quest.cpp", category = "quests", promptKey = "PROMPT_QUEST", style = "reward", notes = "Requires selected player" })
A:RegisterCommand({ id = "quest_remove", labelKey = "CMD_QUEST_REMOVE", command = ".quest remove", security = S.ADMINISTRATOR, source = "cs_quest.cpp", category = "quests", promptKey = "PROMPT_QUEST", dangerous = true, style = "danger", notes = "Requires selected player" })
A:RegisterCommand({ id = "quest_reward", labelKey = "CMD_QUEST_REWARD", command = ".quest reward", security = S.ADMINISTRATOR, source = "cs_quest.cpp", category = "quests", promptKey = "PROMPT_QUEST", style = "reward", notes = "Requires selected player" })
A:RegisterCommand({ id = "recovery_revive", labelKey = "CMD_REVIVE", command = ".revive", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", action = "ReviveSmart", style = "reward" })
A:RegisterCommand({ id = "recovery_respawn", labelKey = "CMD_RESPAWN", command = ".respawn", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", style = "reward" })
A:RegisterCommand({ id = "recovery_repair", labelKey = "CMD_REPAIR", command = ".repairitems", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", style = "reward" })
A:RegisterCommand({ id = "recovery_unstuck", labelKey = "CMD_UNSTUCK", command = ".unstuck", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", style = "reward" })
A:RegisterCommand({ id = "recovery_recall", labelKey = "CMD_RECALL", command = ".recall", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", style = "utility" })
A:RegisterCommand({ id = "recovery_combatstop", labelKey = "CMD_COMBATSTOP", command = ".combatstop", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", style = "utility" })
A:RegisterCommand({ id = "recovery_dismount", labelKey = "CMD_DISMOUNT", command = ".dismount", security = S.PLAYER, source = "cs_misc.cpp", category = "recovery", style = "utility" })
A:RegisterCommand({ id = "recovery_unaura", labelKey = "CMD_UNAURA", command = ".unaura", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "recovery", promptKey = "PROMPT_AURA", style = "utility" })
A:RegisterCommand({ id = "server_info", labelKey = "CMD_SERVER_INFO", command = ".server info", security = S.PLAYER, source = "cs_server.cpp", category = "system", style = "utility" })
A:RegisterCommand({ id = "server_motd", labelKey = "CMD_SERVER_MOTD", command = ".server motd", security = S.PLAYER, source = "cs_server.cpp", category = "system", style = "utility" })
A:RegisterCommand({ id = "saveall", labelKey = "CMD_SAVEALL", command = ".saveall", security = S.GAMEMASTER, source = "cs_misc.cpp", category = "system", style = "reward" })
A:RegisterCommand({ id = "commands", labelKey = "CMD_COMMANDS", command = ".commands", security = S.PLAYER, source = "cs_misc.cpp", category = "system", style = "utility" })
A:RegisterCommand({ id = "help", labelKey = "CMD_HELP", command = ".help", security = S.PLAYER, source = "cs_misc.cpp", category = "system", promptKey = "PROMPT_HELP", style = "utility" })
A:RegisterCommand({ id = "server_corpses", labelKey = "CMD_SERVER_CORPSES", command = ".server corpses", security = S.ADMINISTRATOR, source = "cs_server.cpp", category = "system", style = "utility" })
A:RegisterCommand({ id = "server_set_motd", labelKey = "CMD_SET_MOTD", command = ".server set motd", security = S.ADMINISTRATOR, source = "cs_server.cpp", category = "system", promptKey = "PROMPT_MOTD", style = "utility" })
A:RegisterCommand({ id = "server_restart", labelKey = "CMD_RESTART", command = ".server restart", security = S.ADMINISTRATOR, source = "cs_server.cpp", category = "system", lifecycle = true, promptKey = "PROMPT_SECONDS", dangerous = true, style = "danger" })
A:RegisterCommand({ id = "server_restart_cancel", labelKey = "CMD_RESTART_CANCEL", command = ".server restart cancel", security = S.ADMINISTRATOR, source = "cs_server.cpp", category = "system", lifecycle = true, dangerous = true, style = "danger" })
A:RegisterCommand({ id = "server_shutdown", labelKey = "CMD_SHUTDOWN", command = ".server shutdown", security = S.ADMINISTRATOR, source = "cs_server.cpp", category = "system", lifecycle = true, promptKey = "PROMPT_SECONDS", dangerous = true, style = "danger" })
A:RegisterCommand({ id = "server_shutdown_cancel", labelKey = "CMD_SHUTDOWN_CANCEL", command = ".server shutdown cancel", security = S.ADMINISTRATOR, source = "cs_server.cpp", category = "system", lifecycle = true, dangerous = true, style = "danger" })
A:RegisterCommand({ id = "language_window", labelKey = "CMD_LANGUAGE_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "system", action = "OpenLanguageWindow", style = "utility" })
A:RegisterCommand({ id = "integration_window", labelKey = "CMD_INTEGRATION_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "system", action = "OpenIntegrationsWindow", style = "utility" })
A:RegisterCommand({ id = "playerbot_window", labelKey = "CMD_PLAYERBOT_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "system", action = "OpenPlayerBotWindow", style = "disabled" })
A:RegisterCommand({ id = "teleport_category_open", labelKey = "CMD_TELEPORT_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "teleports", action = "OpenTeleportWindow", style = "utility" })
A:RegisterCommand({ id = "profession_window", labelKey = "CMD_PROFESSION_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "professions", action = "OpenProfessionWindow", style = "utility" })
A:RegisterCommand({ id = "database_window", labelKey = "CMD_DATABASE_WINDOW", command = "", security = S.PLAYER, source = "addon", category = "database", action = "OpenDatabaseWindow", style = "utility" })

A.CommandMeta = {
    accountSecurity = {
        userReported = 9,
        gamemaster = S.GAMEMASTER,
        administrator = S.ADMINISTRATOR,
        readyForQuestMutation = true,
        note = "Configured operator value 9 is above the core SEC_ADMINISTRATOR enum value 3; the addon does not elevate server permissions.",
    },
    sources = {
        gm = "src/server/scripts/Commands/cs_gm.cpp",
        cheat = "src/server/scripts/Commands/cs_cheat.cpp",
        modify = "src/server/scripts/Commands/cs_modify.cpp",
        misc = "src/server/scripts/Commands/cs_misc.cpp",
        character = "src/server/scripts/Commands/cs_character.cpp",
        quest = "src/server/scripts/Commands/cs_quest.cpp",
        tele = "src/server/scripts/Commands/cs_tele.cpp",
        go = "src/server/scripts/Commands/cs_go.cpp",
        lookup = "src/server/scripts/Commands/cs_lookup.cpp",
        learn = "src/server/scripts/Commands/cs_learn.cpp",
        server = "src/server/scripts/Commands/cs_server.cpp",
    },
    playerbot = { verified = false, blocked = true, reason = "Server POC boot/game gates are pending" },
}
